@startuml
'https://plantuml.com/sequence-diagram

前端 -> 缓存: 取得实体
alt 缓存中存在实体
    缓存 -> 前端: 返回实体可监听流
    前端 -> 前端: 监听流
    缓存 -> 后端: 检查更新
    后端 -> 缓存: 返回检查更新结果
    alt 有更新
        缓存 -> 缓存: 更新缓存
    end
else 缓存中不存在实体
    缓存 -> 后端: 取得实体
    后端 -> 缓存: 返回实体
    缓存 -> 前端: 返回实体可监听流
    前端 -> 前端: 监听流
end
@enduml