# Author: 闫刚 (yes7rose@sina.com)
# Cargo.toml (c) 2020
# Desc: workspace 工作空间
# Created:  2020-11-16T02:08:10.711Z
# Modified: !date!

[workspace]
members = [
    "account",
    "auth",
    "cash_core",
    "cash_result",
    "configs",
    "database",
    "entity",
    "property_field",
    "event",
    #    "server",
    "service_handles",
    "majordomo",
    "manage_define",
    "define_utils",
    "managers",
    # "minit",
    "message",
    "procedure",
    "view",
    "work",
]

exclude = ["server", ]
