@startuml
'https://plantuml.com/sequence-diagram

autonumber

客户端 -> 服务端: 文件上传首个包, 不包含文件数据块
服务端 -> 服务端: 检查文件上传状态是否存在, 更新上传状态

服务端 --> 客户端: 下一个数据块的编号
客户端 -> 服务端: 发送对应编号的数据块
服务端 -> 服务端: 校验数据块,写入文件流
客户端 <-- 服务端: 下一个数据块的编号

客户端 -> 服务端: 发送编号为-1的数据块，表示已经发送完了
服务端 -> 服务端: 写入缓存, 关闭文件流
服务端 -> 服务端: 校验文件
服务端 --> 客户端:  -1表示接收完成, 0表示需要重新发送

客户端 -> 服务端: 关闭发送流，或重新上传
@enduml
