#
# 管理定义模板
#

# 管理名, 对应数据库的表或者集合
name = "accounts"

# 数据描写 或者 模式
[schema]
# 通用属性
id = "String"
name = "String"
creator_id = "String"
create_timestamp = "String"
modifier_id = "String"
modify_timestamp = "String"
owner = "String"
groups = "List"

# 访问控制
view_rule = "Map"

# 特有属性
country_code = "UInt32"
phone = "UInt64"

include_views_rules = "List"
exclude_views_rules = "List"


# 初始记录
# 每个记录都需要指定 _id owner_id
[items]
root = { id = "8610000000000", creator_id = "8610000000000", owner_id = "8610000000000", country_code = 86, phone = 10000000000, name = "root", password = "root", groups = ["1000000"] }


