/*
地理地区
*/

syntax = "proto3";
package cashmere;

import "name.proto";

enum AreaLevel {
    Country = 0;
    Province = 1;
    City = 2;
    County = 3;
    Town = 4;
    Village = 5;
    Unknown = 6;
}

message NewAreaRequest {
    Name name = 1;
    string parent_id = 2;
    string code = 3;
    AreaLevel level = 4;
}
message NewAreaResponse {
    string result = 1;
}

message EditAreaRequest {
    string area_id = 1;
    string new_parent_id = 3;
    AreaLevel new_level = 4;
}
message EditAreaResponse {
    string result = 1;
}

// 地址
message Address {
    string country_id = 1;
    string province_id = 2;
    string city_id = 3;
    string county_id = 4;
    string town_id = 5;
    string village_id = 6;
    // 详细地址, 如街道、门牌号等, {语言: 地址}，不在使用编码
    map<string, string> details = 7;
}