@startuml
'https://plantuml.com/class-diagram

class 消息系统 {
    终端表
    会话表
    设置表
}
note right: 管理终端表，\n管理会话表

class 终端代理 {
    终端编号

    创建会话()
    监听会话()
    申请加入会话()
    邀请其他终端加入会话()
    发送消息到会话()
}
note right: 存在特殊用途的终端，\n如系统终端，工程终端

' 有特殊用途的会话
' 会话能被终端查看
' 终端向会话发送消息
' 会话中可以有多个终端
' 会话可以只被监听，不需要加入会话
class 会话 {}

' 消息发送到会话
class 消息 {}

@enduml
