[package]
name = "entity"
version = "0.3.0"
authors = ["yes7rose <yes7rose@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = {path="../database"}
cash_core = {path="../cash_core"}
configs = {path="../configs"}
manage_define = {path="../manage_define"}

chrono = { version = "0.4.19", features = ["serde"] }
tokio = {version = "0.2.23", features = ["stream"]}
mongodb = "1.1.1"
serde = "1.0.117"
serde_derive = "1.0.117"
linked-hash-map="0.5.3"
