[package]
name = "dependencies_sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.5.0"
tonic = { version = "0.7.2", features = ["tls"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.11"
toml = { version = "0.5.8", features = ["preserve_order"] }
parking_lot = "0.12.1"
fs4 = { version = "0.5.4", features = ["tokio-async"] }
md-5 = "0.10.1"
log = "0.4.17"
bytes = "1.4"
hex = "0.4.3"
serde = "1.0.131"
serde_derive = "1.0.131"
linked-hash-map="0.5.3"
