[package]
name = "minit"
version = "0.1.0"
authors = ["闫刚 <7470718@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cash_core = { path = "../cash_core" }
configs = { path = "../configs" }
database = { path = "../database" }
entity = { path = "../entity" }


linked-hash-map = { version = "0.5.3", features = ["serde_impl"] }
toml = "0.5.7"
futures = "0.3.8"
chrono = "0.4.19"
tokio = "0.2.23"
clap = "3.0.0-beta.2"

bson = "1.1.0"

# mongodb = "1.1.1"

# [dependencies.mongodb]
# version = "1.1.1"
# default-features = false
# features = ["sync"]

