[package]
name = "managers"
version = "0.4.1"
authors = ["yes7rose <yes7rose@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cash_core = {path="../cash_core"}
cash_result = {path="../cash_result"}
database = {path = "../database"}
entity = {path="../entity"}
configs = {path="../configs"}
event = {path="../event"}
manage_define = {path="../manage_define"}

async-trait = "0.1.41"
parking_lot = "0.11.0"
serde = "1.0.117"
serde_derive = "1.0.117"
linked-hash-map = { version = "0.5.3", feature = ["serde_impl"] }
bson = "1.1.0"
tokio = "0.2.23"

# logging
log = "0.4"
simplelog = "0.8"