#
# 通用属性，不做管理定义
#

id = 00000
name_map = { zh = "一般属性", en = "general" }

# 描写，模式
schema = [
  # 通用属性
  # common
  { data_type = "String", name_map = { zh = "编号", en = "id" }, removed = false },
  { data_type = "List", name_map = { zh = "实体名", en = "name" }, removed = false },
  { data_type = "String", name_map = { zh = "创建人", en = "creator" }, removed = false },
  { data_type = "Int64", name_map = { zh = "创建时间戳", en = "create_timestamp" }, removed = false },
  { data_type = "String", name_map = { zh = "修改人", en = "modifier" }, removed = false },
  { data_type = "Int64", name_map = { zh = "修改时间戳", en = "modify_timestamp" }, removed = false },
  { data_type = "String", name_map = { zh = "主人", en = "owner" }, removed = false },
  { data_type = "String", name_map = { zh = "组", en = "groups" }, removed = false },
  { data_type = "List", name_map = { zh = "数据", en = "datas" }, removed = false },
  { data_type = "List", name_map = { zh = "已删除数据", en = "datas_removed" }, removed = false },
  { data_type = "List", name_map = { zh = "评论", en = "comments" }, removed = false },
]


# 事件定义
[events]

# 队列定义
[queues]
event_queue = []
massage_queue = []

# 初始实体
[items]

# 映像规则
[view_rules]
[view_rules.manage]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.collection]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.1000]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1001]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1002]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1003]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1004]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1005]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1006]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1007]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1008]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1009]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.2008]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.2009]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.2010]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.2011]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.2012]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [
], write_filters = [
] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
