#
#  语言编码
#

id = 10006
name_map = { zh = "语言编码", en = "languages_codes" }
is_searchable = false
description = "语言编码"

# 数据描写 或者 模式
schema = [
  { data_type = "String", name_map = { zh = "编码", en = "code" }, removed = false },
  { data_type = "String", name_map = { zh = "母语名", en = "native" }, removed = false },
]

[view_rules]

[view_rules.manage]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.collection]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.1000]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.1001]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.1002]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.1003]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.1004]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.1005]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.1006]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.1007]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.1008]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1009]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1010]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1011]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.2001]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

[view_rules.schema.2002]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }

# 初始实体
[items]
1000 = { 1000 = "1000", 1002 = "8610000000000", 1001 = { zh = "中文", en = "Chinese" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "zh", 2002 = "中文" }

1001 = { 1000 = "1001", 1002 = "8610000000000", 1001 = { zh = "英文", en = "English" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "en", 2002 = "English" }

1003 = { 1000 = "1003", 1002 = "8610000000000", 1001 = { zh = "法语", en = "French" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "fr", 2002 = "Français" }

1004 = { 1000 = "1004", 1002 = "8610000000000", 1001 = { zh = "德语", en = "German" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "de", 2002 = "Deutsch" }

1005 = { 1000 = "1005", 1002 = "8610000000000", 1001 = { zh = "意大利语", en = "Italian" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "it", 2002 = "Italiano" }

1006 = { 1000 = "1006", 1002 = "8610000000000", 1001 = { zh = "日语", en = "Japanese" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "ja", 2002 = "日本語" }

1007 = { 1000 = "1007", 1002 = "8610000000000", 1001 = { zh = "朝鲜语", en = "Korean" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "ko", 2002 = "한국어" }

1008 = { 1000 = "1008", 1002 = "8610000000000", 1001 = { zh = "西班牙语", en = "Spanish" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "es", 2002 = "Español" }

1009 = { 1000 = "1009", 1002 = "8610000000000", 1001 = { zh = "阿拉伯语", en = "Arabic" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "ar", 2002 = "العربية" }

1010 = { 1000 = "1010", 1002 = "8610000000000", 1001 = { zh = "俄语", en = "Russian" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "ru", 2002 = "Русский" }

