# 
# 阶段
# 

id = 10018
name_map = { zh = "工作阶段", en = "phases" }

# 描写，模式
schema = [
  { data_type = "String", name_map = { zh = "工作编号", en = "procedure_id" }, removed = false },
  { data_type = "String", name_map = { zh = "状态", en = "status" }, removed = false },
  { data_type = "Int64", name_map = { zh = "开始时间", en = "start_time" }, removed = false },
  { data_type = "Int64", name_map = { zh = "计划时长", en = "plan_duration" }, removed = false },
  { data_type = "Int64", name_map = { zh = "实际时长", en = "real_duration" }, removed = false }
]

[queues]
event_queue = []
massage_queue = []

[events]

[items]
3dasset = { 1000 = "1001", 1002 = "8610000000000", 1001 = "3dasset", 1006 = "8610000000000", 1007 = [
  "10000",
], 2001 = [
  "概念",
  "设计",
  "制作",
] }

[view_rules]
[view_rules.manage]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.collection]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.1000]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1001]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1002]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1003]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1004]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1005]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1006]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "OwnerWrite", read_filters = [
], write_filters = [
] }
[view_rules.schema.1007]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1008]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1009]
10000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1010]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1011]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
# { zh = "阶段表", en = "phases" }
[view_rules.schema.2001]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
