#
# 日历帐本
# 记录实体相关日历信息的帐本
#

id = "日历帐本"
name_map = { zh = "日历帐本", en = "calendar_books" }
description = { zh = "用于记录某个实体的日历信息" }


# 数据描写 或者 模式
schema = [
  { data_type = "String", name_map = { zh = "管理", en = "manage_id" }, removed = false },
  { data_type = "String", name_map = { zh = "实体", en = "entity_id" }, removed = false },
  # 对同一实体不同帐本的标记，用于区分不同帐本
  { data_type = "String", name_map = { zh = "标记", en = "mark" }, removed = false },
]

# 初始实体
[items]


[view_rules]

[view_rules.manage]
admin = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "InVisible", write_rule = "InVisible", read_filters = [

], write_filters = [
] }
[view_rules.collection]
admin = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "InVisible", write_rule = "InVisible", read_filters = [

], write_filters = [
] }

[view_rules.schema.1000]
admin = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1001]
admin = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1002]
admin = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1003]
admin = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1004]
admin = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1005]
admin = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1006]
admin = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1007]
admin = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1008]
admin = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1009]
admin = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
], write_filters = [
] }
[view_rules.schema.1010]
admin = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1011]
admin = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }


[view_rules.schema.1200]
admin = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
] }
user = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
  "OnlyOwner",
] }
