#
# 地区定义
#
# 地理区域

id = 10023
name_map = { zh = "国家", en = "countries" }

# 数据描写 或者 模式
schema = [
  { data_type = "String", name_map = { zh = "母语名", en = "native" }, removed = false },
  # 国家0级，省直辖市1级，
  { data_type = "String", name_map = { zh = "编码", en = "code" }, removed = false },
  { data_type = "String", name_map = { zh = "电话区号", en = "phone_area_code" }, removed = false },
  { data_type = "List", name_map = { zh = "所用语言", en = "languages" }, removed = false },
]

[view_rules]
[view_rules.manage]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.collection]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.1000]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1001]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
[view_rules.schema.1002]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
[view_rules.schema.1003]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1004]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1005]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1006]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1007]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1008]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1009]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1010]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }
[view_rules.schema.1011]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.2001]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.2002]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.2003]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

[view_rules.schema.2004]
10000 = { read_rule = "Read", write_rule = "Write", read_filters = [
  "NoLimit",
], write_filters = [
  "NoLimit",
] }
10001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [
  "NoLimit",
], write_filters = [
] }

# 初始实体
[items]
cn = { 1000 = "cn", 1002 = "8610000000000", 1001 = { zh = "中国", en = "China" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "中国", 2002 = "cn", 2003 = "86", 2004 = [
  "zh",
] }

us = { 1000 = "us", 1002 = "8610000000000", 1001 = { zh = "美国", en = "United States" }, 1006 = "8610000000000", 1007 = [
  "10000",
], 1008 = [
], 1900 = [
], 1200 = false, 2001 = "United States", 2002 = "us", 2003 = "1", 2004 = [
  "en",
] }
