[package]
name = "service_common_handles"
version = "0.4.1"
authors = ["yangang <7470718@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked-hash-map = { version = "0.5.6", feature = ["serde_impl"] }
async-trait = "0.1.58"
futures = "0.3.13"
tokio = { version = "1.21.2" }
tokio-stream = "0.1.11"
h2 = "0.3"
tonic = { version = "0.7.2", features = ["tls"] }
prost = "0.10.4"
chrono = "0.4.19"
bson = "2.6.1"
serde = "1.0.131"
serde_derive = "1.0.131"
log = "0.4.14"
rust-i18n= "1.0"
once_cell = "1.8.0"

account = { path = "../account" }
cash_core = { path = "../cash_core" }
cash_result = { path = "../cash_result" }
data_server = { path = "../data_server" }
configs = { path = "../configs" }
majordomo = { path = "../majordomo" }

managers = { path = "../managers" }
manage_define = { path = "../manage_define" }
auth = { path = "../auth" }
entity = { path = "../entity" }
property_field = { path = "../property_field" }
view = { path = "../view" }
request_utils = { path = "../request_utils" }
