[database]
address = "localhost"
port = 27017
name = "cashmere_db"

[server]
root_dir = "."
address = "127.0.0.1"
port = "8800"

# 加密
use_tls = false
secret_code = "$camshere*soft*warm*smooth*beauty$"
login_limit = 2

# root user
root_id = "8610000000000"
admin_group = "admin"

# 默认语音
language_code = "zh"

# 日志位置
log_dir = "log"
log_level = "debug"

# 分页最大容量
max_page_size = 20

[tls]
server_key_path = "tls/server.key"
server_ca_path = "tls/server.crt"
client_ca_path = "tls/client.crt"

[manages]
# 游客可以访问的管理列表
public_manages = [
  "语言编码",
  "国家编码",
  "手机区号",
]
# 普通用户不可访问的管理列表
forbid_manages = ["编号器", "事件服务"]

[search_engine]
# zh: 索引存储位置
index_root_dir = "tantivy"
# zh: 提交时间间隔，根据修改繁忙程度设置, 单位为 秒
writer_commit_interval = 15
# zh: 写缓存块，根据索引大小设置, 单位为 字节
memory_budget_in_bytes = 15000000
# zh: 不可搜索管理表
unsearchable_manages = ["编号器", "人", "管理", "帐号", "事件服务", "通知栏帐号对", "帐号发送端对"]

[data_server]
root_dir_path = "data_root"
# 文件最大大小, 16MB
max_file_size = 16777216
# 文件集最大数量, 1000
max_set_size = 1000
# 文件序列最大数量
max_sequence_length = 10000
# 最大文件上传连接
max_file_upload_number = 256
# 最大文件下载连接
max_file_download_number = 256
# 块最大大小，1024*128=128KB
transfer_chunk_size = 131072
# 内部文件路径，不需要通过服务器上传文件, 可将文件直接存储到目标位置
internal_root_dir_map = { "windows" = "X:/data_root/dir", "linux" = "/mnt/data_root/dir", "macos" = "/mnt/data_root/dir" }

# 文件上传路径形式，可将文件上传到指定目录, 目前只支持 
# manage["", "manage_id"], stage["", stage, stage_id], version["", version,version_id], 
# specs不能为空且目前只能为id，
# data不能为空且目前只能为id，
file_path_format = { "manage" = "manage_id", "specs" = "specs_id", "data" = "data_id", "stage" = "", "version" = "" }

[event_service]
max_concurrent_queue = 100
max_event_type_count = 100
max_listener_instance_count = 100
