[package]
name = "service_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dependencies_sync ={ path = "../dependencies_sync", features = ["futures", "tonic"] }
manage_define ={ path = "../manage_define" }
