#
# 账户定义
#

id = 10001
name = { Cn = "账号", En = "accounts" }

# 描写，模式
schema = [
    { data_type = "String", name = { Cn = "地区码", En = "country_code" }, removed = false },
    { data_type = "String", name = { Cn = "电话", En = "phone" }, removed = false },
    { data_type = "String", name = { Cn = "密码", En = "password" }, removed = false },
    { data_type = "Bool", name = { Cn = "是否停用", En = "stopped" }, removed = false },
    # utc timestamp list, 记录登录时间点, 登录则更新记录, 旧的token将过期
    { data_type = "List", name = { Cn = "登录时间戳", En = "login_timestamps" }, removed = false },
]


[queues]
event_queue = ["account_event_queue"]
massage_queue = ["account_message_queue"]

[events]
before_create = { manage = "account", name = "before_create", target_queues = ["account_event_queue"] }
after_create = { manage = "account", name = "after_create", target_queues = ["account_event_queue"] }

[items]
root = { 1000 = "8610000000000", 1001 = "root", 1002 = "8610000000000", 1006 = "8610000000000", 1007 = ["1000000"], 2008 = "86", 2009 = "10000000000", 2010 = "$argon2i$v=19$m=4096,t=3,p=1$MjAyMC0xMC0yMVQwOTozMToxNC44OTAwMDgyMDArMDA6MDA$GbdGP8CA82iPyEfKeh7rWZ8R9xGQBgBT3xGTklQ2I/c" }
user = { 1000 = "8610000000001", 1001 = "user", 1002 = "8610000000000", 1006 = "8610000000001", 1007 = ["1000001"], 2008 = "86", 2009 = "10000000001", 2010 = "$argon2i$v=19$m=4096,t=3,p=1$MjAyMC0xMC0yM1QwMzozNzoyOS4yNjUxMjc1MDArMDA6MDA$2eLIIwlj1iPheol0xtpBZFmeUt/39afvNmLXVMi+35Q" }

[view_rules]

[view_rules.manage]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }

[view_rules.collection]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }

[view_rules.schema.1000]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1001]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1002]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1003]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1004]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1005]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1006]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1007]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1008]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1009]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }

[view_rules.schema.2001]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.2002]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.2003]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "OwnerWrite", read_filters = [], write_filters = [] }
[view_rules.schema.2004]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.2005]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = [], write_filters = [] }
