#
# 显示模板定义
#

id = 10012
name = { Cn = "显示设置", En = "show_settings" }

# 描写，模式
schema = [
    { data_type = "String", name = { Cn = "管理编号", En = "manage"}, removed = false },
    { data_type = "Map", name = { Cn = "设置", En = "settings"}, removed = false },
    { data_type = "List", name = { Cn = "隐藏属性", En = "hidden_schemas"}, removed = false },
]

manage = "String"
settings = "Map"
hidden_schemas = "List"

[queues]
event_queue = []
massage_queue = []

[events]

[items]

[view_rules]
[view_rules.manage]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }
[view_rules.collection]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "InVisible", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }

[view_rules.schema.1000]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1001]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1002]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1003]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1004]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1005]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1006]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "OwnerWrite", read_filters = [], write_filters = [] }
[view_rules.schema.1007]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1008]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }

[view_rules.schema.2001]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.2002]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.2003]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
