#
# 映像规则定义
#

id = 10015
name = { Cn = "映像规则", En = "view_rules" }

# 描写，模式
schema = [
    # manage, entity, schema 三个层级
    # -----读
    # 不可见        InVisible,
    # 全部可读      Read,
    # 只组的 可读    GroupRead,
    # 只主的 可读    OwnerRead,
    #------写
    # 不可见             InVisible,
    # 全部可写          Write,
    # 只组的可写        GroupWrite,
    # 只主的 可写       OwnerWrite,
    # -----过滤
    # 无限制        NoLimit,
    # 主 所有       OwnerALl,
    # 组 所有       GroupALl,
    # 只有组的       OnlyGroup,
    # 只有主的      OnlyOwner,
    { id = 2008, data_type = "Map", name = { Cn = "管理级", En = "manage"}, removed = false },
    { id = 2009, data_type = "Map", name = { Cn = "属性级", En = "collection"}, removed = false },
    { id = 2010, data_type = "Map", name = { Cn = "实体级", En = "entity"}, removed = false },
]

[queues]
event_queue = []
massage_queue = []

[events]

[items]

[view_rules]
id = 10015
name = { Cn = "映像规则", En = "view_rules" }

[view_rules.manage]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }
[view_rules.collection]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }

[view_rules.schema.1000]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = ["GroupALl"], write_filters = [] }
[view_rules.schema.1001]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1002]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1003]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1004]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1005]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1006]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1007]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.1008]
1000000 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.2008]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.2009]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }
[view_rules.schema.2010]
1000000 = { read_rule = "Read", write_rule = "Write", read_filters = [], write_filters = [] }
1000001 = { read_rule = "Read", write_rule = "InVisible", read_filters = [], write_filters = [] }

