[package]
name = "work"
version = "0.1.0"
authors = ["yes7rose <yes7rose@sina.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = {path = "../database"}
entity = {path = "../entity"}
cash_core = {path = "../cash_core"}
cash_result = {path = "../cash_result"}
procedure = {path = "../procedure"}
manage_define = {path = "../manage_define"}

bson = "2.4.0"
serde = "1.0.131"
serde_derive = "1.0.131"
