[package]
name = "work"
version = "0.1.0"
authors = ["yes7rose <yes7rose@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manage = {path = "../manage"}
database = {path = "../database"}
entity = {path = "../entity"}
cash_core = {path = "../cash_core"}
procedure = {path = "../procedure"}

bson = "1.1.0"
serde = "1.0.117"
serde_derive = "1.0.117"