[package]
name = "request_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# proc-macro = true

[dependencies]
tonic = "0.7.2"
# quote = "1.0.9"
# syn = "1.0.72"

auth ={ path = "../auth" }