[package]
name = "view"
version = "0.1.0"
authors = ["yes7rose <yes7rose@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
database = { path = "../database" }
account = { path = "../account" }

auth = { path = "../auth" }
entity = { path = "../entity" }
cash_core = { path = "../cash_core" }
cash_result = { path = "../cash_result" }
manage_define = { path = "../manage_define" }

tokio = { version = "0.2.23", features = ["full"] }
linked-hash-map = { version = "0.5.3", features = ["serde_impl"] }
parking_lot = "0.11.0"
mongodb = "1.1.1"
serde = "1.0.117"
serde_derive = "1.0.117"
